spring:
  application:
    name: document-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  main:
    allow-bean-definition-overriding: true
  s3:
    region: ap-south-1
    access-key: aws-access-key
    secret-key: aws-secret-key
    bucket: mybucketabcd